language: node_js
node_js:
  - "6"
  - "8"



script: npm run build && npm run test

# Submit Coverage Status to coveralls.io
after_script:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/coveralls
